name: "Discord Message Sender"
author: "Michael MacDonald"
description: "Greet someone and record the time"
inputs:
  webhook_url:
    description: Discord webhook URL
    required: true
  message:
    description: Message to send to Discord
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.message }}
